### ISSUE TITLE
Error pop-up while using Chef

### ISSUE THREAD

**Issue by nath-3** [nilaymaj/esolang-park#3]
While I was trying to use the Chef language, the following error popped up (telling me to create an issue here):

![Error message on Esolang Park](https://github.com/nilaymaj/esolang-park/assets/125344598/f4b1a2d0-4b19-47ad-a204-98b367a7a325)
**[Worker] TypeError: Cannot read properties of undefined (reading 'line')**
`TypeError: Cannot read properties of undefined (reading 'line')
    at nt (https://esolangpark.vercel.app/workers/chef.js:1:14561)
    at J (https://esolangpark.vercel.app/workers/chef.js:1:10974)
    at t.validateCode (https://esolangpark.vercel.app/workers/chef.js:1:21397)
    at t.validateCode (https://esolangpark.vercel.app/workers/chef.js:1:2941)
    at b (https://esolangpark.vercel.app/workers/chef.js:1:6573)
    at https://esolangpark.vercel.app/workers/chef.js:1:24366
    at https://esolangpark.vercel.app/workers/chef.js:1:6063
    at Object.next (https://esolangpark.vercel.app/workers/chef.js:1:6168)
    at https://esolangpark.vercel.app/workers/chef.js:1:5104
    at new Promise (<anonymous>)`

I've had this error a few times now, and it always pops up eiter while trying to specify the ingredients or while typing the recipe title. I'm not too sure how to reproduce it, though.

**Comment by nilaymaj** [comment]
Hey, thanks a lot for posting this! I'll take a look at what's breaking here.
